project:
  type: website
  output-dir: docs

website:
  favicon: pic.jpg
  title: ""
  navbar:
    right:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: posts.qmd
        text: DATA_SCIENCE-BLOGS
      - href: health.qmd
        text: HEALTH_BLOGS
 
  page-footer:
    background: light
    right:
      - "Copyright 2023, Sujan Bhattarai"
    left: 
      - icon: github
        href: https://github.com/Sujan-Bhattarai12
    
format:
  html:
    theme: 
      - styles.scss
    mainfont: Georgia 
    css: styles.css
    toc: true 



