project:
  type: website
  output-dir: docs

website:
  favicon: pic.jpg
  title: ""
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: featured_projects.qmd
        text: DS-projects
      - href: certifications.qmd
        text: Certificates
      - href: about.qmd
        text: About
    
format:
  html:
    theme: 
      - styles.scss
    mainfont: Verdana 
    css: styles.css



