project:
  type: website
  output-dir: docs

website:
  title: "Sujan Bhattarai &#128187"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: trestles
    css: styles.css
    toc: true



