---
title: "About Me"
---

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Website</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 20px;
    }
    .about-section {
      max-width: 600px;
      margin: 0 auto;
    }
  </style>
</head>
<body>

<div class="about-section">
👋
I'm Sujan Bhattarai, a passionate Data Science student currently pursuing my degree at the University of California, Santa Barbara, based in CA.

🌐 Portfolio Website

📧 Contact:
University Email: sujan@ucsb.edu
Personal Email: sujanbhattarai.jr@gmail.com

🔍 About Me:
I am dedicated to exploring the realms of data science, leveraging my skills to derive meaningful insights from complex datasets. I had a non-tech background during my undergrad, but I self-studied programming and mathematics, passed a couple of tech job interviews, and Worked as a Clinical Data analyst for a year. Now, My academic journey at UCSB is tech-based and I spend 10 hours exploring and learning tech skills.

💻 Portfolio Highlights:
Feel free to explore my website to discover projects showcasing my proficiency in <b>Machine Learning, CLI interface, Apache Based SQL(Hive & Impala), data manipulation, exploratory data analysis, predictive modeling, Forecasting</b> and more. Each project reflects my commitment to applying data science techniques to solve real-world problems.

🤝 Let's Connect:
I am open to collaborations, discussions, and networking opportunities. Whether you have questions about my projects or want to explore potential partnerships, feel free to reach out. Looking forward to connecting with fellow data enthusiasts!
</div>

</body>
</html>
